In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv(r'C:\Users\Brigita\Downloads\StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,72
1,female,group C,some college,standard,completed,69,90,90
2,female,group B,master's degree,standard,none,90,95,95
3,male,group A,associate's degree,free/reduced,none,47,57,57
4,male,group C,some college,standard,none,76,78,78

## Create Index

In [3]:
import numpy as np
import random

In [4]:
# creating non repetitive values for the index
new_index = np.arange(0, 1000)
new_index

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
       182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194,
       195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207,
       208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
       221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233,
       234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246,
       247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259,
       260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272,
       273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285,
       286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298,
       299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311,
       312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324,
       325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337,
       338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350,
       351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363,
       364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376,
       377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389,
       390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402,
       403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415,
       416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428,
       429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441,
       442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454,
       455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467,
       468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480,
       481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493,
       494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506,
       507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519,
       520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532,
       533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545,
       546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558,
       559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571,
       572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584,
       585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597,
       598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610,
       611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623,
       624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636,
       637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649,
       650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662,
       663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675,
       676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688,
       689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701,
       702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714,
       715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727,
       728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740,
       741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753,
       754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766,
       767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779,
       780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792,
       793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805,
       806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818,
       819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831,
       832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844,
       845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857,
       858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870,
       871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883,
       884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896,
       897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909,
       910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922,
       923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935,
       936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948,
       949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961,
       962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974,
       975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987,
       988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999])

In [5]:
# shuffling the indexes
random.shuffle(new_index)
new_index

array([262, 659, 443, 820, 258, 889, 248, 779, 888, 411, 745, 861,  89,
       871, 767, 919, 185, 539, 233, 191, 743, 166, 117, 649, 954, 505,
       813, 194, 695, 148,   2, 289, 785, 519,  77, 683,  23, 890, 451,
       759,  76, 696, 255, 950, 305, 205, 514, 647, 676, 617, 652, 864,
       739, 674, 111, 965, 494, 428, 390, 664, 256, 981, 282, 463, 847,
       857, 524, 134, 856, 741, 307, 983, 522, 727, 343, 493, 595, 960,
       446, 525,  83, 156, 429, 551,  46, 953, 718,  90, 398, 634, 345,
       786, 612, 912, 106, 869, 733,   7, 259, 766, 487, 293, 881, 594,
       985, 821, 909, 550,  62, 559, 850, 470,  70, 969, 704, 572, 995,
       580, 835, 922, 497, 815, 100, 165, 640, 362, 662, 891, 916, 724,
       762, 506, 886, 971, 453, 214, 602, 994, 978, 540, 643, 905, 263,
       427,  71, 809, 271, 302, 164, 666, 200, 128, 120, 279, 455, 382,
       734, 826, 690, 344, 929,  60, 384, 432, 902, 887, 269, 825,  31,
       201, 188, 538,  52, 520, 808, 879, 213, 333, 247, 507, 782, 975,
       731, 145, 132, 855, 119, 393, 498, 987, 138, 639, 464, 306, 878,
       311, 811, 817, 932, 484, 903, 726, 665, 897, 868, 842, 544, 375,
       661, 963, 294, 719, 481,  79, 364, 570,  73, 122, 834, 569,  80,
       299, 222, 287, 329,  67, 980, 104, 358, 621, 126, 884, 736, 206,
       678,  22,  43,  64, 436, 277, 212, 913, 301, 529, 593, 313, 935,
       882, 361, 274, 938,  75, 563, 412, 399, 253, 290, 342, 862, 642,
       644, 252, 123,  40, 947, 959, 863, 385, 235, 288, 276, 894, 697,
       415, 321, 679, 685,  99, 348, 730, 102, 793, 173, 752, 328,  87,
       162,  32, 714, 921, 706, 107, 351, 323, 129, 934, 445, 153, 872,
       370,  95, 553, 227, 347, 363, 314, 866, 413,  45, 951, 449, 336,
       160, 491, 341,  33, 204, 309, 371, 546, 246, 270,   3, 744, 601,
       728, 283, 224, 692, 326, 400, 541, 780, 836, 844, 990, 923, 798,
        74, 312, 749, 424, 784, 168, 972, 610, 940, 388, 232, 318, 426,
       715,  28, 238, 663, 395, 159, 404, 582, 171,  25,  92, 545, 575,
       105, 286,  47, 729, 433, 581,  19, 711, 280, 920,  36, 196, 548,
       416, 113,  97,  17, 176, 843, 597, 184, 116, 829, 147, 814, 970,
        18,  21, 623,  57,  69, 552, 430, 794, 875, 462, 492, 797, 417,
       789, 620, 816, 883,  65, 651, 625, 402, 949, 365, 999, 207,  29,
       353, 488,  13, 788, 841, 907, 121, 210, 930, 910, 763,  26, 755,
        66, 892, 167, 346, 155, 591,  58, 367, 725, 986, 645, 568, 576,
       944, 338, 368, 776, 260, 435, 189, 588, 770, 483, 340, 137, 638,
       278, 758,  94, 899, 320, 838,  27, 976, 272, 900, 837, 112, 226,
       966, 630, 511, 457, 852, 675, 478, 962, 618, 521, 298, 853, 461,
       790, 936, 504, 637, 914, 702, 377, 542, 828, 578, 499, 275, 308,
       761, 442, 925, 187, 723, 495, 310, 460, 325, 144, 708, 284, 564,
       818, 516, 982, 476, 560, 693, 319, 500, 592, 778, 988, 928, 565,
       322, 956, 152,  35,  56, 669, 819, 968, 807,  44, 831, 401, 330,
       477, 149, 712,  91, 650, 296, 406, 849, 420, 682, 996, 240, 673,
       571, 596, 441, 810, 350, 440, 974, 127, 408, 528, 158, 216, 740,
       806, 877, 792, 133, 535,   0, 561,  55, 349, 480, 396, 691, 303,
       577, 710, 924,  88, 754, 103, 438, 795, 893, 677, 474, 796, 110,
       383, 182, 655, 452, 141, 771, 703, 468,  63, 536, 717,  48,   5,
       146, 709, 389, 742,  30, 851, 218, 641, 418, 357, 845,  82, 607,
       469, 239, 716, 486, 993, 667, 700,  37, 317, 765, 352,  81, 686,
       865, 518, 656,  20, 750, 556, 199, 386, 590, 684, 753, 720, 502,
       787, 527, 606, 485, 456, 472, 774, 927, 532, 747, 236, 812, 266,
       381, 482, 217, 566, 407, 244,   6, 379, 172, 241, 229, 896, 231,
       225,  12, 781, 114, 537, 125, 830, 680, 197, 170, 549, 431, 827,
       605, 237,  51, 437, 908,   4, 587,  14, 501, 598, 444, 619, 234,
       295, 694, 180, 874, 802, 633, 579, 394, 967, 946, 609, 186, 973,
       760, 941, 115, 228, 374, 490, 615, 157, 334, 151, 603, 554, 297,
        72, 450, 195, 245, 670, 177, 681, 503, 101, 558, 906, 707,  86,
       672, 772, 738, 391, 757, 977, 751, 783, 631, 118,  15, 174, 626,
       979, 331, 687, 515, 161, 699, 584, 622, 668, 804, 291, 130, 701,
       360, 335, 945, 898,  10, 183, 454, 824, 124, 356, 414, 833, 777,
       870, 211, 880, 193, 324, 459, 648, 964, 624, 215, 722,  61, 169,
       208, 530, 773, 405, 422,  49, 800, 403, 658, 198,  24, 108, 823,
       918, 439, 859, 448, 555, 369, 223, 267, 573, 799, 447, 281, 315,
       209, 915, 273, 378, 355, 840, 822, 423, 992, 599, 984, 140, 533,
       179, 292, 628, 713, 409, 264, 943, 419, 737, 627, 249, 250, 230,
       933, 873, 567, 764, 467,  42, 339, 203, 660, 646, 242, 471,  98,
       756,  38, 316, 589, 268, 517, 671, 939, 735, 616, 803,  96, 359,
       926, 917, 839, 265, 425, 955, 698, 611, 585, 832, 952, 608,  41,
       586,   1, 635, 135, 387,  34, 221, 181, 629, 688, 178, 220, 997,
       473, 768, 958, 366, 769, 434, 636, 957, 372,  85, 931, 876, 261,
       805, 254,  93, 465, 458, 219, 523, 513,  78, 746, 475, 142,  53,
        39, 583, 136, 846,   8, 937, 848, 613, 748, 885, 998,  16, 300,
       791, 989, 562, 858, 901, 397, 948,  59, 732, 337, 327, 854,  11,
       421, 131, 285, 653, 139, 991, 961,   9, 512, 190, 202,  50, 466,
       410, 705, 373, 479, 654, 109, 860, 775, 557, 376, 867, 904, 175,
       508, 243, 510, 942, 657, 543, 380, 163,  68, 534, 632, 604, 689,
       600,  84, 251, 150, 526, 531, 354, 801, 509, 257, 143, 547, 332,
       911, 392, 721, 304, 574, 154, 192, 489,  54, 614, 496, 895])

In [6]:
# create a new column with new index
df_exams['new_index'] = new_index
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
0,female,group B,bachelor's degree,standard,none,72,72,72,262
1,female,group C,some college,standard,completed,69,90,90,659
2,female,group B,master's degree,standard,none,90,95,95,443
3,male,group A,associate's degree,free/reduced,none,47,57,57,820
4,male,group C,some college,standard,none,76,78,78,258
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,99,489
996,male,group C,high school,free/reduced,none,62,55,55,54
997,female,group C,high school,free/reduced,completed,59,71,71,614
998,female,group D,some college,standard,completed,68,78,78,496
999,female,group D,some college,free/reduced,none,77,86,86,895

## Set Index

In [7]:
# set new_index column as index of the dataframe series instead of 1,2,3,4...
df_exams.set_index('new_index', inplace=True)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
262,female,group B,bachelor's degree,standard,none,72,72,72
659,female,group C,some college,standard,completed,69,90,90
443,female,group B,master's degree,standard,none,90,95,95
820,male,group A,associate's degree,free/reduced,none,47,57,57
258,male,group C,some college,standard,none,76,78,78
...,...,...,...,...,...,...,...,...
489,female,group E,master's degree,standard,completed,88,99,99
54,male,group C,high school,free/reduced,none,62,55,55
614,female,group C,high school,free/reduced,completed,59,71,71
496,female,group D,some college,standard,completed,68,78,78
895,female,group D,some college,free/reduced,none,77,86,86

## Sort Index

In [8]:
# sort descending by index
df_exams.sort_index(ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
999,male,group B,some high school,standard,completed,63,67,67
998,male,group D,high school,free/reduced,none,69,70,70
997,male,group D,bachelor's degree,free/reduced,none,55,46,46
996,female,group D,associate's degree,standard,none,82,95,95
995,female,group B,bachelor's degree,free/reduced,none,75,85,85
...,...,...,...,...,...,...,...,...
4,male,group B,high school,standard,none,60,68,68
3,female,group C,some college,standard,none,71,81,81
2,female,group D,some college,standard,none,69,74,74
1,male,group B,associate's degree,standard,completed,82,84,84
0,male,group B,bachelor's degree,free/reduced,none,48,51,51