In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv(r'C:\Users\Brigita\Downloads\StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,72
1,female,group C,some college,standard,completed,69,90,90
2,female,group B,master's degree,standard,none,90,95,95
3,male,group A,associate's degree,free/reduced,none,47,57,57
4,male,group C,some college,standard,none,76,78,78

## Selecting multiple columns

In [3]:
# select 2 columns using [[]]. we will get the columns in the order that we write in the dataframe ([[...]]).
df_exams[['gender', 'math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [4]:
# check out the data type of the selection
type(df_exams[['gender', 'math score']])

pandas.DataFrame

In [5]:
# select 2 or more columns using [[]]
df_exams[['gender', 'math score', 'reading score', 'writing score']]

     gender  math score  reading score  writing score
0    female          72             72             72
1    female          69             90             90
2    female          90             95             95
3      male          47             57             57
4      male          76             78             78
..      ...         ...            ...            ...
995  female          88             99             99
996    male          62             55             55
997  female          59             71             71
998  female          68             78             78
999  female          77             86             86

[1000 rows x 4 columns]

In [ ]:
# ! we can't select 2 or more columns with the "."
df_exams.'gender', 'math score'