In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv(r'C:\Users\Brigita\Downloads\StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,72
1,female,group C,some college,standard,completed,69,90,90
2,female,group B,master's degree,standard,none,90,95,95
3,male,group A,associate's degree,free/reduced,none,47,57,57
4,male,group C,some college,standard,none,76,78,78

## Sort a dataframe

In [3]:
# sort by one column
df_exams.sort_values('math score')

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,17
980,female,group B,high school,free/reduced,none,8,24,24
17,female,group B,some high school,free/reduced,none,18,32,32
787,female,group B,some college,standard,none,19,38,38
145,female,group C,some college,free/reduced,none,22,39,39
...,...,...,...,...,...,...,...,...
623,male,group A,some college,standard,completed,100,96,96
625,male,group D,some college,standard,completed,100,97,97
962,female,group E,associate's degree,standard,none,100,100,100
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100

In [4]:
# sort descending by one column
df_exams.sort_values('math score', ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
451,female,group E,some college,standard,none,100,92,92
458,female,group E,bachelor's degree,standard,none,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,100
623,male,group A,some college,standard,completed,100,96,96
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,39
787,female,group B,some college,standard,none,19,38,38
17,female,group B,some high school,free/reduced,none,18,32,32
980,female,group B,high school,free/reduced,none,8,24,24
59,female,group C,some high school,free/reduced,none,0,17,17

In [5]:
# sort descending by multiple columns
df_exams.sort_values(['math score', 'reading score'], ascending=False)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
149,male,group E,associate's degree,free/reduced,completed,100,100,100
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,97
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,39
787,female,group B,some college,standard,none,19,38,38
17,female,group B,some high school,free/reduced,none,18,32,32
980,female,group B,high school,free/reduced,none,8,24,24
59,female,group C,some high school,free/reduced,none,0,17,17

In [8]:
# sort descending by multiple columns and update dataframe using inplace
df_exams.sort_values(['math score', 'reading score'], ascending=False, inplace=True)

In [10]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
149,male,group E,associate's degree,free/reduced,completed,100,100,100
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,97
...,...,...,...,...,...,...,...,...
145,female,group C,some college,free/reduced,none,22,39,39
787,female,group B,some college,standard,none,19,38,38
17,female,group B,some high school,free/reduced,none,18,32,32
980,female,group B,high school,free/reduced,none,8,24,24
59,female,group C,some high school,free/reduced,none,0,17,17

In [12]:
# sort descending with a key function  sort_values() with a key function uses lowercase temporarily just to determine 
# the sort order—it never alters the actual text stored inside your DataFrame
# Pandas creates lowercased copies behind the scenes to rank the rows, but it outputs the original capitalized values (group A, group E)
df_exams.sort_values(['race/ethnicity'], ascending=True, key=lambda col:col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
623,male,group A,some college,standard,completed,100,96,96
539,male,group A,associate's degree,standard,completed,97,92,92
546,female,group A,some high school,standard,completed,92,100,100
571,male,group A,bachelor's degree,standard,none,91,96,96
702,male,group A,bachelor's degree,standard,completed,87,84,84
...,...,...,...,...,...,...,...,...
807,female,group E,high school,free/reduced,none,41,45,45
383,female,group E,some high school,free/reduced,none,38,49,49
616,female,group E,bachelor's degree,standard,none,37,45,45
895,female,group E,some high school,free/reduced,none,32,34,34
76,male,group E,some high school,standard,none,30,26,26