In [1]:
import pandas as pd

In [3]:
# reading the csv file
df_exams = pd.read_csv(r'C:\Users\Brigita\Downloads\StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,72
1,female,group C,some college,standard,completed,69,90,90
2,female,group B,master's degree,standard,none,90,95,95
3,male,group A,associate's degree,free/reduced,none,47,57,57
4,male,group C,some college,standard,none,76,78,78

## Rename Column

In [4]:
# rename column and overwrite values of the dataframe
df_exams = df_exams.rename(columns={'gender':'Gender'})

In [5]:
# rename multiple columns and update the dataframe with inplace parameter
df_exams.rename(columns={'math score':'MS', 'reading score':'RS', 'writing score':'WS'}, inplace=True)

In [6]:
# show dataframe
df_exams.head()

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS
0,female,group B,bachelor's degree,standard,none,72,72,72
1,female,group C,some college,standard,completed,69,90,90
2,female,group B,master's degree,standard,none,90,95,95
3,male,group A,associate's degree,free/reduced,none,47,57,57
4,male,group C,some college,standard,none,76,78,78

## Rename Index

In [7]:
# rename index 0, 1 and 2 and update the dataframe
df_exams.rename(index={0:'A', 1:'B', 2:'C'}, inplace=True)

In [8]:
# show first 3 rows
df_exams.head(3)

,Gender,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS
A,female,group B,bachelor's degree,standard,none,72,72,72
B,female,group C,some college,standard,completed,69,90,90
C,female,group B,master's degree,standard,none,90,95,95