In [1]:
import pandas as pd

In [2]:
# reading the csv file
df_exams = pd.read_csv(r'C:\Users\Brigita\Downloads\StudentsPerformance.csv')
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,72
1,female,group C,some college,standard,completed,69,90,90
2,female,group B,master's degree,standard,none,90,95,95
3,male,group A,associate's degree,free/reduced,none,47,57,57
4,male,group C,some college,standard,none,76,78,78

## Adding a new column

#### assign()

When to use assign?

- Add multiple columns in a single line of code
- When you need to over-write the values of an existing columns (best practice)
  
It returns a new object (a copy) with all the original columns in addition to the new ones

In [3]:
import numpy as np

In [4]:
# create random numbers for our new score columns
score1 = np.random.randint(1, 100, size=1000)
score2 = np.random.randint(1, 100, size=1000)

In [5]:
# create a series using the random numbers
series1 = pd.Series(score1, index=np.arange(0, 1000))
series2 = pd.Series(score2, index=np.arange(0, 1000))

In [14]:
# using assign() method generates a new copy of the DataFrame with these additional columns included. overwrites the original variable df_exams with this updated DataFrame.
df_exams = df_exams.assign(score1=series1, score2=series2)

In [15]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,14,group B,bachelor's degree,standard,none,72,72,72,14,30
1,female,80,group C,some college,standard,completed,69,90,90,80,80
2,female,28,group B,master's degree,standard,none,90,95,95,28,20
3,male,22,group A,associate's degree,free/reduced,none,47,57,57,22,39
4,male,36,group C,some college,standard,none,76,78,78,36,43
...,...,...,...,...,...,...,...,...,...,...,...
995,female,89,group E,master's degree,standard,completed,88,99,99,89,24
996,male,26,group C,high school,free/reduced,none,62,55,55,26,33
997,female,34,group C,high school,free/reduced,completed,59,71,71,34,6
998,female,26,group D,some college,standard,completed,68,78,78,26,78
999,female,14,group D,some college,free/reduced,none,77,86,86,14,61

#### insert()
Inserts a new column at a specific position or index.

In [9]:
# using insert() to add a column at a specific position
df_exams.insert(1, 'test', series1)

In [10]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,score1,score2
0,female,14,group B,bachelor's degree,standard,none,72,72,72,14,30
1,female,80,group C,some college,standard,completed,69,90,90,80,80
2,female,28,group B,master's degree,standard,none,90,95,95,28,20
3,male,22,group A,associate's degree,free/reduced,none,47,57,57,22,39
4,male,36,group C,some college,standard,none,76,78,78,36,43
...,...,...,...,...,...,...,...,...,...,...,...
995,female,89,group E,master's degree,standard,completed,88,99,99,89,24
996,male,26,group C,high school,free/reduced,none,62,55,55,26,33
997,female,34,group C,high school,free/reduced,completed,59,71,71,34,6
998,female,26,group D,some college,standard,completed,68,78,78,26,78
999,female,14,group D,some college,free/reduced,none,77,86,86,14,61